version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    container_name: monitoring
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    networks:
      - arrowhead-network
  monitoring_mysql:
    container_name: monitoring_mysql
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=THIS_WILL_BE_YOUR_CONTAINERS_ROOT_PW
    command: --init-file /app/init.sql
    volumes:
      - ./init.sql:/app/init.sql
      - monitoring_mysql:/var/lib/mysql
      #- ./sql:/docker-entrypoint-initdb.d/
    ports:
      - 3307:3306
    networks:
      - arrowhead-network
volumes:
  monitoring_mysql:
    external: true  
networks:
  arrowhead-network:
   name: arrowhead-network
